version: '3'

services:
  nginx:
    image: owasp/modsecurity-crs:3.3.4-nginx-alpine-202304160904
    restart: always
    volumes:
      - ./templates/conf.d/default.conf:/etc/nginx/templates/default.conf.template
      - ./templates/includes/proxy_backend.conf.template:/etc/nginx/templates/proxy_backend.conf.template
      - ./templates/includes/location_common.conf.template:/etc/nginx/templates/location_common.conf.template
      - ./modsecurity/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
    ports:
      - 80:80
      - 443:443
    environment:
      - PORT=80
      - SSL_PORT=443
      - SERVER_NAME=example.com
      - BACKEND=http://backend-app:8080
      - NGINX_ALWAYS_TLS_REDIRECT=off
      - PROXY_SSL_CERT=/etc/nginx/conf/server.crt
      - PROXY_SSL_CERT_KEY=/etc/nginx/conf/server.key
      - PROXY_SSL_DH_BITS=2048
      - PROXY_SSL_PROTOCOLS=TLSv1.2 TLSv1.3
      - PROXY_SSL_CIPHERS=ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
      - PROXY_SSL_PREFER_CIPHERS=on
      - PROXY_SSL_OCSP_STAPLING=on
      - PROXY_SSL_OCSP_STAPLING=on
      - PROXY_SSL_VERIFY=off
      - REAL_IP_HEADER=X-Forwarded-For
      - METRICS_ALLOW_FROM=127.0.0.0/24
      - METRICS_DENY_FROM=all
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
