version: '3'
services:  
  #Nginx Service
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: proxy_nginx
    restart: always
    tty: true
    environment:
      - TZ=America/Fortaleza
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./modsec:/etc/nginx/modsec
      - ./ssl:/etc/ssl
